import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Salesio Minecraft Server</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.logo_parent}>
            <Image
              className={styles.logo}
              src="/Minecraft.jpg"
              alt="Minecraft Server Logo"
              fill
              priority
            />
          </div>
          <ol>
            <li>Start Minecraft with version <code>1.21.1</code>.</li>
            <li>Get started by joining Server IP <code>122.208.16.184</code>.</li>
          </ol>

          <div className={styles.ctas}>
            <Link href='./wiki/wiki_home' className={styles.secondary}>Document</Link>
            <a
              href="https://discord.gg/aDDEtbxbSK"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Join Discord
            </a>
          </div>
          これは開発中のページです
        </main>
      </div>
    </>
  );
}
